name: Keep Streamlit App Awake

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"

  # Allows you to run it manually from GitHub
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app
        run: |
          curl -L --fail --retry 3 https://cana-demo.streamlit.app/
